# Test your FastAPI endpoints

###

POST http://127.0.0.1:52062/tasks/
Content-Type: application/json

{
  "feedback": "Nice",
  "metadata": {
    "source_platform": "Twitter"
  }
}
###

GET http://127.0.0.1:52062/tasks/4bd2399fd9e7fa02482ea3e086b1de41625621bbbbead63bbbaa2ea093b17255
Accept: application/json

###

GET http://127.0.0.1:8000/statistics
Accept: application/json

###
